#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Acme\Command\DefaultCommand;
use Symfony\Component\Console\Application;
use App\Command\GetPaymentDatesCommand;

$application = new Application('payment-dates', '0.0.1');
$command = new GetPaymentDatesCommand();

$application->add($command);

$application->setDefaultCommand($command->getName(), true);
$application->run();